### PR TITLE
Settings, saving and getting the correct values

### PR DESCRIPTION
**Pull request by artfuld**
Some settings did not repopulate when viewing settings.
Also changed the size of the modal for HTML Input

### CODE REVIEW

**Comment by artfuld** [comment]
#405 should be fixed with this

**Comment by artfuld** [comment]
Fixes for #329 and #408

**Comment by frozendnn** [comment]
@artfuld , how do we get all these changes you have made? Is there is a new release with these changes? Thanks for doing this.

**Comment by artfuld** [comment]
@frozendnn I will do a couple of more testing to see if I can fix the problem with the admin panel and then I will release 6.3.3. If you need/want it now it's all here on github :).

**Pull request merged**
