### PR TITLE
Issues/issue 439

### PR DESCRIPTION
**Pull request by hismightiness**
Resolves issue #435

### CODE REVIEW

**Comment by ChrisHammond** [comment]
Not sure it's appropriate to completely hijack the existing copyrights that were provided by DNN Corp's ownership of the project, turned over to community. Wouldn't you typically leave those existing copyrights in place and add new for the Community copyright?

**Comment by artfuld** [comment]
Hey, nice job!

Not sure if I understand the *.*-part in your ignore file. When adding a folder isn't it allready taking everything in that folder?

**Comment by hismightiness** [comment]
@artfuld I agree.... Without the wildcard though, git kept trying to commit the packages folder.  :( 

@ChrisHammond I don't think it matters.  This project is a hodgepodge of copyright statements.  No one ever actually maintained them.  I don't care either way, really.

**Comment by donker** [comment]
@ChrisHammond Not sure if anyone wishes to attach their name to this code ... #justsayin

**Pull request closed without merging**
