### PR TITLE
Handle AllUsers role (issue #353)

### PR DESCRIPTION
**Pull request by sleupold**
needs to be tested

### CODE REVIEW

**Comment by artfuld** [comment]
Just a thought, wouldn't it be better to add that role to all users? Just
in case there's somewhere else that permission is checked?
Den 23 jan. 2016 1:24 em skrev "Sebastian Leupold" <notifications@github.com

**Comment by sleupold** [comment]
including unauthenticated ones?
this "virtual role" has no users assigned, it could be faked in AF API (which bypasses DNN Security nearly completely), but it would only slowdown the permission check. Another "shortcut" would be checking userID -1 (unauthenticated user) and RoleID -3 ("Unauthenticated Users" role), but the userid is not accessible in this procedure.
Permission handling in AF is neither straight forward nor efficient - storing for each forum and group a string with a delimited list of RoleIDs and not converting it in the controller into a list makes it difficult to handle, especially in installations with a large number of roles. I would prefer a record per forum/group and role - there is no big difference in retrieving 1 record or a limited set of it.

**Comment by artfuld** [comment]
It used to look like this
image
Not sure when it changed from that to what we have today. But whoever did it left some tables in there :/.

I was thinking more along the line of adding -1 to the users role whenever they are added/checked. Just in case there's somewhere else that they the permissions. I'll try it out when I get the time!

**Comment by artfuld** [comment]
What I was talking about before was something like this.
in UserController.cs line 286
change from 
string RoleIds = "";
to
string RoleIds = "-1;";

That should always add the virtual role "All users" to every call for a permission check.

**Comment by sleupold** [comment]
right, and it will always start the full permission check - done right, if "all users" role is granted permission, no role/group membership or individual permission need to be checked at all - same, if userid > 0 and RegisteredUsers role is granted or userId = -1 and UnauthenticatedUsers (-3) are granted permission. 
Btw. storing role list in a string is crap anyways (in API and database), this needs to be overhauled.

**Comment by sleupold** [comment]
regarding permissions in the database, it contains same data, but in an unorthodox way. DNN would store a permission per forum/group and user/role in a row, I would use a single row per forum/group and role/user, holding all permissions (mostly like the table you listed above).

**Comment by artfuld** [comment]
I agree about the security system is slow and hard to work with.

If I was certain that every call for a permission check was using the method that you changed in this I would also agree that the code you changed is the best way to do it, as you say checking early to see if  the role -1 is there would save a couple of loops.
But what about HasAccess on line 560?

If you say that the HasPermission method is the only place that this need to be added then I will gladly add it to the code.
I'm not here to argue, just want this to be looked over from all sides :).

**Comment by sleupold** [comment]
@artfuld 
thanks for the heads up, I fixed HasAccess to use same logic.

**Pull request merged**
