### PR TITLE
Unresolved & My Resolved + minor fix (poll spacer skin compatibility)

### PR DESCRIPTION
**Pull request by cmsfrotter**
additions according to #253 
- added unresolved & myresolved views to the controlbar
- created a new 6.1.5 sqldataprovider file for associated SPs
- added it to install routine
- rearranged toolbar order slighty
- fixed an issue with giant poll spacer if used portal skin is auto-scaling images

### CODE REVIEW

**Comment by supermansrf** [comment]
@cmsfrotter I hate to ask this of you, but I'm not going to include this pull in 6.2 (new beta I'm going to compile tonight).  Git is saying that this can't be automatically merged and I don't know what I'm doing.  

Once I release 6.2 tonight, can you please take a look at these and see if you can generate a new pull that will work with the new UI?  I'm afraid that what they did with the UI changes is going to mess up one or two things you fixed.  

I'm hoping to have this done before I go to bed.  The guys made significant changes to the UI.  You will see what I'm talking about if you test 6.2.  Let me know if you have any questions.

**Comment by supermansrf** [comment]
@cmsfrotter will you take a look at what you did here and please try to work it in with the most recent updates?  I believe that you have fixed a few things that have been causing issues, but I can't automatically merge this and don't really know what all you were doing.  It looks like you do.  

Please?

**Comment by cmsfrotter** [comment]
Sorry I did not answer this yet. Sure thing, I'll take a look at it as soon as I'm able to

**Comment by mitchelsellers** [comment]
Given the older nature of this release, closing this pull request.  As it would need to be revisited regardless.  I would welcome a new review if it is deemed necessary.

**Pull request closed without merging**
